name: ğŸ—ï¸ Terraform Deploy to AWS --

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  # workflow_dispatch:   # âœ… Manual trigger from GitHub Actions tab
  workflow_dispatch:
    inputs:
      action:
        description: "Select Terraform action to perform"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy


jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
    

    steps:
      # -----------------------------
      # Step 1. Checkout repository
      # -----------------------------
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4
      # -----------------------------
      # Step 3. Setup Terraform
      # -----------------------------
      - name: âš™ï¸ Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: ğŸ”‘ Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIAQR5EO6LI6J4LKB7J
          aws-secret-access-key: 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

      # -----------------------------
      # Step 4. Terraform Init
      # -----------------------------
      - name: ğŸª£ Terraform Init
        run: terraform init

      # -----------------------------
      # Step 5. Terraform Validate
      # -----------------------------
      - name: âœ… Terraform Validate
        run: terraform validate

      # -----------------------------
      # Step 6. Terraform Plan
      # -----------------------------
      - name: ğŸ“œ Terraform Plan
        run: terraform plan

      # -----------------------------
      # Step 7. Terraform Apply (always runs)
      # -----------------------------
      - name: ğŸš€ Terraform Apply
        run: terraform apply -auto-approve
